name: Build

on:
  pull_request:

env:
  NODE_VERSION: 22.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Run Linter
        run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Type Checker
        run: npm run type-check

  unit-tests:
    needs: [ lint, type-check ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Build Library
        run: npm run build
      - name: Run Unit Tests
        run: npm run test
      - name: Run Package Tests
        run: |
          npm run package-check
          npm run package-type-check

  component-tests:
    needs: [ lint, type-check ]
    runs-on: ubuntu-latest
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.53.0-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Run storybook tests
        run: npm run test:storybook

  build-storybook:
    needs: [ unit-tests, component-tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install Packages
        run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Build Library Documentation
        run: npm run docs:build
