# Template used https://superface.ai/blog/npm-publish-gh-actions-changelog
name: Release

on:
  workflow_dispatch:
    # Inputs the workflow accepts. See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
    inputs:
      release_version:
        description: 'Version to release (follow SemVer e.g. 1.0.0)'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git configuration
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "Github Actions on behalf of @${{ github.triggering_actor }}"
      - name: Bump Release Version
        id: releaseVersionUpdate
        run: |
          npm ci
          npx nx release --skip-publish ${{ github.event.inputs.release_version }}
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b release/${{ github.event.inputs.release_version }}
          git push --tags origin release/${{ github.event.inputs.release_version }}
      - name: Merge Release Data via Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Release ${{ github.event.inputs.release_version }}',
              owner,
              repo,
              head: 'release/${{ github.event.inputs.release_version }}',
              base: 'main',
              body: [
                'Adds release data',
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['release', 'automated pr']
            });
      #            await github.rest.pulls.createReview({
      #              owner,
      #              repo,
      #              pull_number: result.data.number,
      #              event: 'APPROVE'
      #            });
      #            await github.rest.pulls.merge({
      #              owner,
      #              repo,
      #              pull_number: result.data.number,
      #              merge_method: 'merge'
      #            });
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_version }}
          generate_release_notes: true

  publish-package:
    needs: [ github-release ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_version }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          # Defaults to the user or organization that owns the workflow file
          scope: '@lion5'
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish To Github Packages
        run: npx nx release publish --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish To NPM Packages
        run: npx nx release publish --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


  publish-documentation:
    needs: [ github-release ]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_version }}
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install Packages
        run: npm ci
      - name: Build Packages
        run: npm run build
      - name: Build Library Documentation
        run: npm run docs:build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './packages/storybook-host/storybook-static/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
